version: '3.8'

services:
  spark-master:
    build: .
    container_name: coleta-cnpj-spark-master
    ports:
      - "4040:4040"
      - "7077:7077"
    volumes:
      - /workspace
    environment:
      - SPARK_MASTER=true
    networks:
      - coleta-cnpj-network

  postgresql:
    image: postgres:13
    container_name: coleta-cnpj-postgres
    environment:
      POSTGRES_USER: spark
      POSTGRES_PASSWORD: spark
      POSTGRES_DB: sparkdb
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - coleta-cnpj-network

networks:
  coleta-cnpj-network:
    driver: bridge

volumes:
  postgresql-data:
    driver: local
